name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        uses: engineerd/setup-minikube@v1
        with:
          minikube-version: latest
          kubectl-version: latest

      - name: Build Docker image
        run: |
          docker build -t balaji2702/example-app:latest .

      - name: Load Docker image into Minikube
        run: |
          minikube docker-env
          docker save balaji2702/example-app:latest | (eval $(minikube docker-env) && docker load)

      - name: Apply Kubernetes configuration
        run: kubectl apply -f deployment.yaml
