name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https ca-certificates curl
          curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update -y
          sudo apt-get install -y kubectl

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
          sudo dpkg -i minikube_latest_amd64.deb

      - name: Start Minikube
        run: minikube start --driver=docker --wait=all

      - name: Build Docker image
        run: |
          docker build -t balaji2702/example-app:latest .

      - name: Load Docker image into Minikube
        run: |
          minikube -p minikube cache add balaji2702/example-app:latest

      - name: Apply Kubernetes configuration
        run: kubectl apply -f deployment.yaml
